site_name: "Logbook"
repo_url: https://github.com/prism-science/logbook
repo_doi: 10.5281/zenodo.17351307
site_url: https://diffuse.science/logbook
site_description: "A logbook for the Diffuse Project"
site_author: "The Diffuse Project"
extra:
  homepage: https://diffuse.science
  homepage_title: The Diffuse Project
  generator: true
extra_css:
  - stylesheets/extra.css
copyright: "&copy; 2025 The Diffuse Project."
theme: 
  logo: assets/diffuse-logo-dark-sm.png
  name: material
  custom_dir: overrides
  palette:
    primary: black
    accent: orange
  features:
#    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.path
    - toc.integrate
plugins:
  - meta
  - tags
  - blog:
      authors: true
      blog_dir: .
      blog_toc: true
      post_url_format: '{file}'
      post_readtime: false
      archive: false
  - mkdocs-jupyter:
     include_source: True # adds a download button for .ipynb
     show_input: False
     no_input: True
     ignore_h1_titles: True # filename will be the title

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.tilde