authors:
  spmeisburger:
    name: Steve Meisburger
    description: Research scientist at Cornell / CHESS
    avatar:  /logbook/assets/authors/meisburger.jpg
    url: https://spmeisburger.github.io
    slug: steve
